---
# Ruby from source playbook

- name: upgrade
  action: apt update_cache=yes upgrade=yes

- name: install ruby dependencies 
  action: apt pkg=$item state=installed
  with_items:
    - build-essential 
    #- zlib1g-dev 
    #- libyaml-dev 
    #- libssl-dev 
    #- libgdbm-dev 
    #- libreadline-dev 
    #- libncurses5-dev 
    #- libffi-dev 
    #- curl 
    #- checkinstall 
    #- libxml2-dev 
    #- libxslt1-dev # The installation document says libxslt-dev, but I guess this is okay
    #- libcurl4-openssl-dev 
    #- libicu-dev

# Install correct version of ruby from source
- name: ensure directory temporary ruby download directory is present
  file: state=directory path=$rubyTmpDir

- name: ensure ruby is downloaded
  get_url: url=$rubyUrl dest=$rubyTmpDir

- name: ensure ruby is extracted
  command: tar -xf $rubyCompressedFile chdir=/tmp/ruby creates=$tmpRubyPath

- name: ensure ruby is configured
  command: ./configure chdir=$tmpRubyPath creates=$tmpRubyPath/Makefile

- name: ensure ruby is compiled
  command: make chdir=$tmpRubyPath creates=$tmpRubyPath/ruby

- name: ensure ruby is installed
  command: make install chdir=$tmpRubyPath creates=/usr/local/bin/ruby
